version: 1.0
provider:
  name: openfaas
  gateway: https://veba02
functions:
  powercli-entermaint:
    lang: powercli
    handler: ./handler
    image: kremerpatrick/veba-powercli-esx-maintenance:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: true
    secrets:
      - vc-hostmaint-config
    annotations:
      topic: EnteredMaintenanceModeEvent, ExitMaintenanceModeEvent